import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import { Footer } from './components/footer/footer'
import { Navbar } from './components/navbar/navbar'


const inter = Poppins({ subsets: ['latin'],
weight:"400" })


export const metadata: Metadata = {
  title: 'MinervaElements',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar/>

      {children}
      
      <Footer/>
      </body>
    </html>
  )
}