import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Header from "./components/Header/Header";
import { Footer } from "./components/Footer/Footer";

const inter = Poppins({ subsets: ["latin"], weight: ["400","500","600","700","800"] });

export const metadata: Metadata = {
  title: "MinervaElements",
  description: "Generated by create next app",
  authors: [
    { name: "Sbleit", url: "https://sbleit.net", },
    { name: "Eli-ezer", url:"", },
  ],
  creator:'Minverva Elements Team'
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
